version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
      - "5678:5678"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
